on:
  pull_request:
name: Unmanaged dependency check
jobs:
  unmanaged_dependency_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Install modules
      shell: bash
      run: .kokoro/build.sh
    - name: Find shared dependencies version
      shell: bash
      run: echo unmanaged-dependencies-check-latest=3.20.0 >> "$GITHUB_OUTPUT"
    - name: Unmanaged dependency check
      uses: googleapis/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check@{{ env.unmanaged-dependencies-check-latest }}
      with:
        bom-path: google-cloud-bigtable-bom/pom.xml
